//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        public static string Broj {
            get {
                return ResourceManager.GetString("Broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih utakmica:.
        /// </summary>
        public static string Broj_odigranih_utakmica {
            get {
                return ResourceManager.GetString("Broj odigranih utakmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova:.
        /// </summary>
        public static string Broj_zabijenih_golova {
            get {
                return ResourceManager.GetString("Broj zabijenih golova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona:.
        /// </summary>
        public static string Broj_zutih_kartona {
            get {
                return ResourceManager.GetString("Broj zutih kartona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        public static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap defaultPlayerImg {
            get {
                object obj = ResourceManager.GetObject("defaultPlayerImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa Code:.
        /// </summary>
        public static string Fifa_Code {
            get {
                return ResourceManager.GetString("Fifa Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gol razlika:.
        /// </summary>
        public static string Gol_razlika {
            get {
                return ResourceManager.GetString("Gol razlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrač:.
        /// </summary>
        public static string Igrac {
            get {
                return ResourceManager.GetString("Igrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        public static string Kapetan {
            get {
                return ResourceManager.GetString("Kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Želite li zatvoriti aplikaciju ?.
        /// </summary>
        public static string lblPitanje {
            get {
                return ResourceManager.GetString("lblPitanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlučeni:.
        /// </summary>
        public static string Neodlučeni {
            get {
                return ResourceManager.GetString("Neodlučeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena reprezentacija.
        /// </summary>
        public static string Omiljena_reprezentacija {
            get {
                return ResourceManager.GetString("Omiljena reprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede:.
        /// </summary>
        public static string Pobjede {
            get {
                return ResourceManager.GetString("Pobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi:.
        /// </summary>
        public static string Porazi {
            get {
                return ResourceManager.GetString("Porazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string Postavke {
            get {
                return ResourceManager.GetString("Postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string Pozicija {
            get {
                return ResourceManager.GetString("Pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz.
        /// </summary>
        public static string Prikaz {
            get {
                return ResourceManager.GetString("Prikaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži utakmicu.
        /// </summary>
        public static string Prikaži_utakmicu {
            get {
                return ResourceManager.GetString("Prikaži utakmicu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni golovi:.
        /// </summary>
        public static string Primljeni_golovi {
            get {
                return ResourceManager.GetString("Primljeni golovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protivnička reprezentacija.
        /// </summary>
        public static string Protivnička_reprezentacija {
            get {
                return ResourceManager.GetString("Protivnička reprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacija:.
        /// </summary>
        public static string Reprezentacija {
            get {
                return ResourceManager.GetString("Reprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shirtImg {
            get {
                object obj = ResourceManager.GetObject("shirtImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika:.
        /// </summary>
        public static string Slika {
            get {
                return ResourceManager.GetString("Slika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za promjenu jezika je potrebno ponovno pokrenuti aplikaciju !.
        /// </summary>
        public static string toolTipContent {
            get {
                return ResourceManager.GetString("toolTipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjeni jezik.
        /// </summary>
        public static string toolTipHeader {
            get {
                return ResourceManager.GetString("toolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni golovi:.
        /// </summary>
        public static string Zabijeni_golovi {
            get {
                return ResourceManager.GetString("Zabijeni golovi", resourceCulture);
            }
        }
    }
}
