//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string btnOdaberi_Text {
            get {
                return ResourceManager.GetString("btnOdaberi.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string btnSortdGoalsScored_Text {
            get {
                return ResourceManager.GetString("btnSortdGoalsScored.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string btnSortedAttendance_Text {
            get {
                return ResourceManager.GetString("btnSortedAttendance.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string btnSortYellowCards_Text {
            get {
                return ResourceManager.GetString("btnSortYellowCards.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DodajIgracaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("DodajIgracaToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string dodajUOmiljeneToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("dodajUOmiljeneToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string engleskiToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("engleskiToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hrvatskiToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("hrvatskiToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ispisToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("ispisToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ispisToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("ispisToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ispisToolStripMenuItem1_Text1 {
            get {
                return ResourceManager.GetString("ispisToolStripMenuItem1.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string labelOdabrani_Text {
            get {
                return ResourceManager.GetString("labelOdabrani.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lblOdaberiReprezentaciju_Text {
            get {
                return ResourceManager.GetString("lblOdaberiReprezentaciju.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string odabirPrinteraToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("odabirPrinteraToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string openFileToolStripMenuIteopenFileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openFileToolStripMenuIteopenFileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string postaviJezikToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("postaviJezikToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string postavkeStraniceToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("postavkeStraniceToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string postavkeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("postavkeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string pregledPrijeIspisaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pregledPrijeIspisaToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string prikaziIgračaToolStripMenuPrikaziIgraca_Text {
            get {
                return ResourceManager.GetString("prikaziIgračaToolStripMenuPrikaziIgraca.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string saveFileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveFileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string toolStripMenuItemObrisiIgraca_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemObrisiIgraca.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string toolStripMenuObrisiSve_Text {
            get {
                return ResourceManager.GetString("toolStripMenuObrisiSve.Text", resourceCulture);
            }
        }
    }
}
